name: OpenPAYGO-Pass-firmware Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get release tag
        id: get_release_tag
        run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Use release tag
        run: echo $RELEASE_TAG
